### ISSUE TITLE
Enrich the Examples section

### ISSUE THREAD

**Issue by adriguir** [dynawo/dynawo#1023]
Move existing non regression tests for DynaSwing.
Add examples for DynaWaltz.
Optionnaly add example for DynaWave.

**Comment by adriguir** [comment]
@rosiereflo did you correct the curves reference for IEEE14 DynaFlow? 
Otherwise I will reopen the issue to push this correction.

**Comment by rosiereflo** [comment]
No I didn't correct it as I prefer you to take a look to make sure that the modification of the simulation time is intended (but I closed the ticket anyway as the main objective is done, but you can reopen it if you prefer).

**Comment by adriguir** [comment]
Then I reopen it.
Yes, I wanted to go to longer simulation time, which is more realistic.
