### ISSUE TITLE
Some improvements in CMakeLists

### ISSUE THREAD

**Issue by gautierbureau** [dynawo/dynawo#1037]
1. be able to compile in Clion
2. Add -O0 in modelica model compilation to have full debug available

**Comment by rosiereflo** [comment]
Hi, do we need this into the v1.2.1 release?

**Comment by gautierbureau** [comment]
It is not very important for it to go in as it is only useful if you want to compile the project and nobody will just checkout v1.2.1 and compile it

**Comment by rosiereflo** [comment]
ok!
