### ISSUE TITLE
Missing TimelineKeys Class

### ISSUE THREAD

**Issue by SoerenLohr** [dynawo/dynawo#1077]
While trying to validate a test model, which contained lines from Dynawo.Electrical.Lines, I encountered the following error:
"[Dynawo.Electrical.Controls.Basics.SwitchOff: 174:7-174:49]: Variable TimelineKeys.LineOpen not found in scope Dynawo.Electrical.Lines.Line$line1." 

Upon further investigation, I found out that there is no TimelineKeys class in the latest version of Dynawo. However, it seems like a lot, if not all, of the SwitchOff classes use TimelineKeys to log events. This prevents the usage of the Electrical models, since the created model can't be flattened/compiled due to missing classes.

Since I don't exactly know what is planned for the SwitchOff Logic, I propose adding the TimelineKeys class in again for the time being to make the models usable and then update the SwitchOff Logic in its entirety.

**Comment by martinscripts** [comment]
Hey dynawo team! 

I am repoening this because I am currently [writing with the developers of OMPython](https://github.com/OpenModelica/OMPython/issues/199) to solve a problem. 
I was asked

> Can you please open a [ticket on the dynawo project](https://github.com/dynawo/dynawo/issues) where you ask the developers to remove the timelineKeys files from .gitignore and manage them properly on the git repository? We will soon add Dynawo to the OMC package manager, and this is essential for the whole thing to work properly in all cases. Thanks!

The missing timelinekeys are a problem for usability by others. 
Let's find a solution for this. What is the reason for the files being included in .gitignore?

**Comment by casella** [comment]
I'll discuss this with @joyelfeghali and try to find a good solution.

**Comment by casella** [comment]
@rosiereflo can you please post a pointer to that?

**Comment by rosiereflo** [comment]
Sure!
https://github.com/dynawo/dynawo/releases/download/v1.5.0/Dynawo_Modelica_Library_v1.5.0.zip

**Comment by joyelfeghali** [comment]
Hello, I opened a new issue #3158 to treat this problem. I will close this one.
