### ISSUE TITLE
Fix name in AcEmulation.mo

### ISSUE THREAD

**Issue by RomainLosseauRTE** [dynawo/dynawo#1191]

**Comment by MarianneSaugierRTE** [comment]
@RomainLosseauRTE what is this dev about? Should it go into the v1.2.1?

**Comment by RomainLosseauRTE** [comment]
I thought that the variable might be supposed to be named PRefSet instead of PSet, maybe this is not urgent

**Comment by adriguir** [comment]
@RomainLosseauRTE @MarianneSaugierRTE what about this? is it ready, postponed or in progress?

**Comment by RomainLosseauRTE** [comment]
It is to be done
