### ISSUE TITLE
Option for current time output 

### ISSUE THREAD

**Issue by adriguir** [dynawo/dynawo#1206]
In the current state, after each iteration the current time is written in a file that is open and closed before and after writing.

It would be nice to only output this time when requested in a specific option in the job file. This option could also indicate how often the print should be updated (every x s in terms of time in the simulation, not real time).

**Comment by rosiereflo** [comment]
A simplified option should be added in v1.2.1 to disable the timetable generation as the mechanism is not thread-safe.
