### ISSUE TITLE
Constraints search and output 

### ISSUE THREAD

**Issue by adriguir** [dynawo/dynawo#1212]
In the current version of the code, constraints are determined, calculated and outwritten in all simulations, whatever is the simulation use case. For some cases, calculating constraints is useless and has a large impact on simulation time (for example in the bus model).

Searching, calculating and determining the constraints should be optional and set by a parameter in the jobs file. It seems quite easy and straightforward to distinguish roots and z equations related to constraints in C++ models but finding an automatic way to do it for Modelica models appear more challenging.

**Comment by rosiereflo** [comment]
isn't this a duplicate of #903 ?

**Comment by adriguir** [comment]
You are right, I haven't noticed that we already had a generic issue around outputs open, my fault.
