### ISSUE TITLE
CPP model ModelStaticVarCompensator has a fixed P equals to zero

### ISSUE THREAD

**Issue by gautierbureau** [dynawo/dynawo#1242]
It would be better to at least get the p we get from the iidm

**Comment by adriguir** [comment]
At this stage and with the infos we have, it's the best that we can do. It means basically switching to a real (B,G) injector in the Cpp model, which can make sense.

It would be nice to be consistent with the Modelica model in terms of behavior for example when the component is turned off.

**Comment by MarianneSaugierRTE** [comment]
We wanted to remove the pseudo dynamic of the static var compensator on the reactive side since a long time. Should I take advantage of this dev to do it and end up with a constant P-Q behavior, as the generator C++ model?

**Comment by adriguir** [comment]
Yes, this is a good idea
