### ISSUE TITLE
[IIDM 1.2] Handle three windings transformers

### ISSUE THREAD

**Issue by adriguir** [dynawo/dynawo#1281]
At the moment, the model for three windings transformers is empty and no transformation to a set of two windings transformers is done.
It means that results for test cases including three windings transformers are erroneous.

A first possible solution would be to convert the three windings transformers to a set of two windings transformers into the data interface.

**Comment by adriguir** [comment]
@rosiereflo @marcochiaramello can we close it?

**Comment by rosiereflo** [comment]
yes :)
