### ISSUE TITLE
Extend the CPP restorative load component to add voltage limitations

### ISSUE THREAD

**Issue by adriguir** [dynawo/dynawo#1311]
In its current state, the restorative load component available in the network model doesn't include any voltage limitations: it means that the restoration is done whatever is the voltage value.
A more realistic model will also implement and use minimal and maximal voltage limitations. Outside these values, the load will then behave as a pure alpha-beta load.

Even if this model's improvement is more realistic, it should remain optional for applications not wanting to use it at first stage (DynaWaltz for example). It means that the values should remain optional in the parameters set and the associated g and z shouldn't be set and evaluated in case the limits are defined.

**Comment by adriguir** [comment]
We can imagine different implementations for this: having an additional generic parameter in the network set to set if limits have to be enforced, having only the max and min values as optional and use this to set the nb of z and g dynamically or any other idea. 

Any opinion @rosiereflo @cossartque @MarianneSaugierRTE @gautierbureau ?

**Comment by rosiereflo** [comment]
I like the second idea: optional min and max per load.

**Comment by cossartque** [comment]
Same as @rosiereflo, I think it is better to have only optional min and max.

**Comment by marcochiaramello** [comment]
same as @rosiereflo too

**Comment by adriguir** [comment]
Update on this issue: it seems the equations written for the long-term voltage stability and for the steady-state problem will differ. A specific load model will certainly be needed, either as a new possibility in the current load model or as a new proper model.
