### ISSUE TITLE
Jobs input file: disabling logs in the first job affects logging in subsequent jobs

### ISSUE THREAD

**Issue by jl-marin** [dynawo/dynawo#1408]
Tested on v1.2.1 (HEAD-4bf05ee), RTE internal version.

it seems that if you suppress all logging in the first job (by removing the `logs` section), then the second job does not produce any logging at all, regardless of its own `logs` section.  Not only that; one can also see changes in how Dynawo writes to stdout.

For instance, this is the console output when fic_JOB.xml contains <logs> entries in both t0 and tFin:
```
$ dynawo-RTE jobs fic_JOB.xml
[INFO] xsd validation will not be used
launching job 'recollement-auto-20200527-1700_t0'
job 'recollement-auto-20200527-1700_t0' succeeded
results are available in /home/marinjl/work/Recollement/QUICK_TEST/./t0/outputs
launching job 'recollement-auto-20200527-1700_tFin'
job 'recollement-auto-20200527-1700_tFin' succeeded
results are available in /home/marinjl/work/Recollement/QUICK_TEST/./tFin/outputs
```

And this is the console output when fic_JOB.xml omits the <logs> entry **only in the t0 job**:
```
$ dynawo-RTE jobs fic_JOB.xml
[INFO] xsd validation will not be used
launching job 'recollement-auto-20200527-1700_t0'
```
(no more output to the console, and no logs created for tFin).

Marianne told me she could also reproduce this behavior.

Regards
JL

**Comment by adriguir** [comment]
@jl-marin thank you for opening the issue
