### ISSUE TITLE
Move logs to Debug

### ISSUE THREAD

**Issue by adriguir** [dynawo/dynawo#1440]
In the current state, some logs are displayed in info while it could be only printed at debug level.

In particular, the mode change details are not really required, as well as the changes in the discrete variables of the network (except connection/disconnection events) and could be moved to the debug level. In addition, these logs are also printed out in the timeline so not really needed there.

**Comment by adriguir** [comment]
Is it fine for you @rosiereflo @MarianneSaugierRTE ?

**Comment by MarianneSaugierRTE** [comment]
Ok!
