### ISSUE TITLE
Add info on frequency value in the log when Dynawo crashes

### ISSUE THREAD

**Issue by MarianneSaugierRTE** [dynawo/dynawo#1445]

**Comment by adriguir** [comment]
A proposal would be to have both a log and a throw if the frequency becomes lower than a certain value (to be defined). The throw could be catched by the calling method and used to output from the simulation with a specific status (frequency collapse for example).

@rosiereflo I suppose it could easily be done by implementing a checkDataCoherence method in the OmegaRef model, checking the value of omega.

**Comment by rosiereflo** [comment]
yes, today the method checkDataCoherence is overriden (and empty) in DYNModelCPPImpl today but it would make sense to add a OmegaRef specific implementation with this check.

**Comment by adriguir** [comment]
BTW, if we want to have a bit of flexibility, we can say that the threshold for frequency collapse is a parameter, read in the par file.

**Comment by rosiereflo** [comment]
> BTW, if we want to have a bit of flexibility, we can say that the threshold for frequency collapse is a parameter, read in the par file.

I totally agree, hard coded threshold are never good

**Comment by adriguir** [comment]
The method checkDataCoherence can be transformed to virtual and not pure virtual and a specific error type is perhaps needed.
