### ISSUE TITLE
Fix issues with 3rd parties

### ISSUE THREAD

**Issue by gautierbureau** [dynawo/dynawo#1760]
- Libxml2 is not found on windows following #1719 
- Some Boost libraries needed by the ones we use are not handled the same way with new cmake and new boost version

**Comment by rosiereflo** [comment]
Are you sure of the ticket that broke the build? this PR is not integrated yet

**Comment by gautierbureau** [comment]
> Are you sure of the ticket that broke the build? this PR is not integrated yet

Yes wrong copy/paste of ticket number
