### ISSUE TITLE
Investigate in models unittests why deleteFactory is not covered

### ISSUE THREAD

**Issue by gautierbureau** [dynawo/dynawo#1762]
Constructor is called and destructor seems not so maybe we need to clarify why and avoid memory leaks if they happen

**Comment by rosiereflo** [comment]
Are you sure it is not an inaccuracy of the coverage? I already saw destructors marked as not covered whereas they were directly called

**Comment by gautierbureau** [comment]
I absolutly don't know... Maybe it is just this and there is nothing to investigate. But as this mechanism is particular I touhght it could come from it

**Comment by rosiereflo** [comment]
I confirm this is a false positive
