### ISSUE TITLE
Study the possibility to remove dependency of ModelicaModels to other solvers than KINSubModel

### ISSUE THREAD

**Issue by gautierbureau** [dynawo/dynawo#1951]
In `Models/CMakeLists.txt` a model depends of dynawo_ModelManager and dynawo_ModelManager depends of dynawo_SolverKINSOL. Mayber we can separate dynawo_SolverKINSOL into two libraries to have KINSubModel in its own library.

**Comment by valleefred** [comment]
Sundials libraries are not found while creating dynawo_SolverKINSOL.dll
