### ISSUE TITLE
Add more models in the NonElectrical library

### ISSUE THREAD

**Issue by cossartque** [dynawo/dynawo#2011]
In NonElectrical/Blocks, the following models should be added (in Continuous or NonLinear depending on the model, the same sort of classification as in the MSL should be used) : 
Add4, ApproximatedDelay, FirstOrderLimiter, FirstOrderWithDelay, FixedBooleanDelay, FlipFlopR, FlipFlopS (with base model, not necessarily in a BaseClassesFolder), IntegratorOrFirstOrder, LeadLag, LimitedIntegrator, LimitedLeadLag, Power, PulseFixedDuration, PulseMinimumDuration.

The package.order and CMakeLists.txt should be updated.

**Comment by ErwanGuichard49** [comment]
Regarding Add4, I wonder if the component MSL Sum could replace it. I have already used it in BaseSEMIPOL. It is parametered with k, a vector. Is that an issue under Dynawo ?
