### ISSUE TITLE
Update release actions to add headers distrib

### ISSUE THREAD

**Issue by gautierbureau** [dynawo/dynawo#2051]

**Comment by rosiereflo** [comment]
isn't this done?

**Comment by gautierbureau** [comment]
No in this workflow https://github.com/dynawo/dynawo/blob/master/.github/workflows/release.yml we only upload the omc version. In the nightly release it is ok on the other hand

**Comment by gautierbureau** [comment]
In fact it would be better to have this before the release. I will do it ASAP
