### ISSUE TITLE
Check consistency when using connectors or types in DynaFlow modelica models

### ISSUE THREAD

**Issue by marcochiaramello** [dynawo/dynawo#2063]
In some DynaFlow models, we use connectors or/and types without a general consistency

**Comment by cossartque** [comment]
We can decide once and for all that:
- for regulation inputs, such as URef, PRef, QRef, tanPhiRef, thetaRef we use "input Types.blabla"
- for everything else, such as sections, taps, UMonitored, N, NQ, we keep connectors as we don't want to add some sort of useless causality.
@adriguir and @marcochiaramello what do you think ?
