### ISSUE TITLE
Some nrt fail in Debug because of an assert in DYNRingBuffer.cpp

### ISSUE THREAD

**Issue by cossartque** [dynawo/dynawo#2064]
The following error is obtained : 
dynawo: /home/cossartque/Projects/dynawo/dynawo/dynawo/sources/Modeler/Common/DYNRingBuffer.cpp:34: void DYN::RingBuffer::add(double, double): Assertion `doubleEquals(queue_.back().second, value)' failed.
/home/cossartque/Projects/dynawo/dynawo/deploy/gcc9/shared/dynawo/bin/launcher : ligne 174 : 135949 Abandon (core dumped) ${DYNAWO} ${ARGS}
Dynawo job failed

The pb is avoided by changing the precision in the jobs file.
I have a test case showing this.

**Comment by rosiereflo** [comment]
This happens when the precision of Dynawo is above the solver precision=> two consecutive time steps from the solver can be seen as equal in Dynawo.
