### ISSUE TITLE
[Performance] Investigate the possibility to remove the mutexes in DYNSubModelFactory

### ISSUE THREAD

**Issue by rosiereflo** [dynawo/dynawo#2153]

**Comment by adriguir** [comment]
Didn't it provide any gain finally or are we blocked due to the not thread safe characteristic of PowSyBl?

**Comment by adriguir** [comment]
Ok, got it from the e-mail.

**Comment by rosiereflo** [comment]
Just so that we have a trace: Removing the mutexes helped with OpenMP performance but not enough as the intensive usage of dlopen and KLU are locking the threads very regurlarly.
