### ISSUE TITLE
Hysteresis without initial equation

### ISSUE THREAD

**Issue by ErwanGuichard49** [dynawo/dynawo#2154]
Create a substitute for the MSL Hysteresis

**Comment by adriguir** [comment]
Why do we need to create a substitute to the MSL block? What is the issue with the initial equation part?

**Comment by ErwanGuichard49** [comment]
The standard block uses a Boolean parameter named pre_y_start. By an initial equation, pre(y) = pre_y_start. If u is between uHigh and uLow, y takes the value pre_y_start. This is not possible under Dynawo, which disregards the initial equation.

**Comment by adriguir** [comment]
Ok, thanks for the additional details.
