### ISSUE TITLE
[Data Interface] Node connection: fix graph exploration and add a tie-breaker 

### ISSUE THREAD

**Issue by rosiereflo** [dynawo/dynawo#2180]
Some existing paths between two nodes are not found with the current implementation of findAllPaths. Moreover when 2 paths with the same length are found, the one with the smallest number of switches to close should be selected.

**Comment by gautierbureau** [comment]
Memory seems to blow up in some cases. Need some investigation

**Comment by rosiereflo** [comment]
Seems logical: now we really find all the paths, so if there are many of them then it will blow up the memory. We should implement a proper Dijkstra.
