### ISSUE TITLE
Investigate why the use of a limiter in an _INIT model doesn't work

### ISSUE THREAD

**Issue by cossartque** [dynawo/dynawo#2198]
In branch 425 of dynawo-rte, a limiter is used in BaseGovernorT2_INIT model (the problematic limiter is limiter1).
This limiter seems to be ignored which causes a bad init and a transient in the nrt (SMIB_GoverEdfTur3cVR4AlstExTkjEdf1) because at init, the output variable is outside the limits and it shouldn't be.

Replacing the limiter with an "if" doesn't work either.

Replacing it with a min and a max combination works.

@ErwanGuichard49 fyi.

**Comment by rosiereflo** [comment]
> We don't rotate the buffers in the local initialization, which leads to not taking into account the limits (the mode of the equations are not changed). Once fixing this, it works. We now need to double check if there is no unexpected side effects with this change.

Do you have a branch I can start with?
