### ISSUE TITLE
Is it relevant to use DTWDistance to compare solverSIM curves in nrt?

### ISSUE THREAD

**Issue by gautierbureau** [dynawo/dynawo#2201]
For `nrt/data/IEEE57/IEEE57_BasicTestCases/IEEE57_3_DisconnectLine` we have a difference in the curves that goes unnoticed and maybe it should have

**Comment by rosiereflo** [comment]
DTW distance is used to compare curve files independently of the solver. Did you compare the curves with the graphical view?

**Comment by gautierbureau** [comment]
> DTW distance is used to compare curve files independently of the solver. Did you compare the curves with the graphical view?

Yes in the graphical view. DTW is good for IDA because we could have a different number of points but sor SIM it should not be the case so a pure difference would be better.
