### ISSUE TITLE
[NRT] Add the possibility to plot the reference curves

### ISSUE THREAD

**Issue by rosiereflo** [dynawo/dynawo#2217]
Add the possibility to plot the values from the reference curve files

**Comment by rosiereflo** [comment]
@ErwanGuichard49 FYI

**Comment by rosiereflo** [comment]
This feature already exists: myEnvDynawo.sh curves-reference <PATH TO JOBS FILE>

**Comment by ErwanGuichard49** [comment]
On my computer, with this line, I get
myEnvDynawo.sh : commande introuvable

Could you show me your myEnvDynawo.sh file ?

Moreover, does this feature exist for dynawo-rte ?

**Comment by ErwanGuichard49** [comment]
This feature exists for dynawo-rte and it works for me, but I would like to plot both the reference and the current output for comparison purposes on the same plot.

**Comment by rosiereflo** [comment]
> This feature exists for dynawo-rte and it works for me, but I would like to plot both the reference and the current output for comparison purposes on the same plot.

got it
