### ISSUE TITLE
CombiTable1Ds in INIT model : inaccurate calculation

### ISSUE THREAD

**Issue by ErwanGuichard49** [dynawo/dynawo#2228]
This issue can be observed  on the models GoverAnsal.mo and GoverAnsal_INIT.mo with the test case nrt/data/SMIB/SMIB_GoverAnsalVRAnsal/SMIB.jobs

There is a difference between the output of the block CombiTable1Ds in the dynamic model and in the initialization model, although the tables and the inputs are identical in the .csv results file.

In GoverAnsal.mo, fHp.u = 0.474747 = Pm0Pu, fHp.y = 0.179899.

In GoverAnsal_INIT.mo, fHp.u = Pm0Pu = 0.474747, fHp.y = 0.17989. This value is used as OpeningHp0 to initialize a LimIntegrator block in the dynamic model.

For fIp, we have fIp.y = 0.112424 in the dynamic model, fIp.y = OpeningIp0 = 0.112417 in the INIT model.

**Comment by cossartque** [comment]
The difference you are talking about here is of about 1e-5 ! So there is no problem for me with the combiTable. I close this issue. I am pretty sure the problem with this model is elsewhere.
