### ISSUE TITLE
Improve error message when error in dyd xml syntaxe for unitDynamicModel

### ISSUE THREAD

**Issue by MarianneSaugierRTE** [dynawo/dynawo#223]
The following syntax is not allowed and the error message is not clear:
`<dyn:unitDynamicModel id="generator"... >`
` ...`
`  </dyn:unitDynamicModel>`

We have to write this:
`<dyn:unitDynamicModel id="generator" ... />`

**Comment by rosiereflo** [comment]
The exception is defined by xerces, unfortunately there is not much we can do here
