### ISSUE TITLE
Evaluate the impact on the transient stability of the use of a dynamic line model

### ISSUE THREAD

**Issue by jalibmon** [dynawo/dynawo#2244]
A classic AC power line using the PI equivalent model, considering the transient mode.

**Comment by cossartque** [comment]
The aim of this work is to:
- Create a dynamic line model (pi line first, taking into account the dynamic behaviour of the inductance and the two capacitances).
- Create the _INIT.mo model related to it. This model calculates all the initial parameters of the dynamic model knowing only LF results (P0, Q0, U0, UPhase0 on both sides of the line).
- Validate the model and its init on a simple Two infinite buses - one line- test case.
- Start the analysis on a SMIB case: one synchronous generator, some lines, and an infinite bus. The idea is to analyse whether the use of a dynamic model for the line changes the stability results (with and without regulations for the SG). A LF calculation needs to be done first.
- Do the same with a grid forming converter
- Do the same with a grid following converter
