### ISSUE TITLE
Non-connected TransferFunction and failed compilation

### ISSUE THREAD

**Issue by ErwanGuichard49** [dynawo/dynawo#2317]
This compilation issue can be recreated by replacing **GoverEdfTur2eBis** by **GoverEdfTur2e** in the dynawo-rte preassembled files 
_GeneratorSynchronousFourWindingsGoverEdfTur2eVRAlst.xml
GeneratorSynchronousFourWindingsGoverEdfTur2eVRAlstTfo.xml_
at line 19 in both files.

The log file points to the _Dyn.cpp file :
_if (iCalculatedVar == 11) /* governor.PmTurHpPu */
{
return (data->simulationInfo->realParameter[235] /* governor.leadLag.bb[2] PARAM */ - ((data->simulationInfo->realParameter[230] /* governor.leadLag.a[2] PARAM */) * (data->simulationInfo->realParameter[236] /* governor.leadLag.d PARAM */))) * (SHOULD NOT BE USED - CALCULATED VAR /* governor.leadLag.x[indexOffset +0] variable */) + (data->simulationInfo->realParameter[236] /* governor.leadLag.d PARAM */) * (x[indexOffset +1]);
}_

In dynawo/sources/Models/Modelica/DynawoRTE/Electrical/Controls/Machines/Governors/Specific/Nuclear/BaseClasses/BaseGovernorN.mo, there is a block TransferFunction named leadLag (see lines 90-91). This block is connected to RealOutput PmTurHpPu (lines 279-280).

In dynawo/sources/Models/Modelica/PreassembledModels/GeneratorSynchronousFourWindingsGoverEdfTur2eVRAlst.xml,
the output PmTurHpPu of model GoverEdfTur2e.mo is connected to nothing. The compilation fails, I guess because of an unknown variable in excess : der(y).

In GoverEdfTur2eBis.mo, the block leadLag is modified so that its vector x becomes a one-component vector i.e. there is not derivative of y.

Could a compilation be made to work with GoverEdfTur2e.mo ?

**Comment by rosiereflo** [comment]
branch 485
