### ISSUE TITLE
Fix bus dynamic model use in dyd

### ISSUE THREAD

**Issue by gautierbureau** [dynawo/dynawo#2343]
If we use a bus model in the dyd with the current behaviour the bus is created also in the network model.

**Comment by rosiereflo** [comment]
I don't think we support a dynamic bus when using a iidm: if we remove the bus from the static network, Dynawo might think one the sides is disconnected and shuts it off

**Comment by rosiereflo** [comment]
cf https://github.com/dynawo/dynawo/issues/548
