### ISSUE TITLE
Enable a proper integrator with variable limits

### ISSUE THREAD

**Issue by ErwanGuichard49** [dynawo/dynawo#2389]
The Dynawo code ought to be modified in order to allow the attached block to be compiled and to run under Dynawo. It involves the derivatives of both inputs limitMax and limitMin.

[IntegratorVariableLimits.txt](https://github.com/dynawo/dynawo/files/8941973/IntegratorVariableLimits.txt)

**Comment by cossartque** [comment]
The way this "ideal" model is written, limitMin and limitMax can not be differentiated. If we filter them, with a small integration time constant, we can use the derivative of limitMinFiltered and limitMaxFiltered. It is quite similar to what is done in slewRateLimiter in the MSL.
This way I pass the build of dynawo.
The simulation however still fails.
I think we can try to go this way

**Comment by cossartque** [comment]
> I have tried several versions of IntegratorVariableLimits with filtered limitMax and limitMin. All of them passed the build Dynawo. Calculating der(limitMaxFiltered) made the dynawo-rte compilation fail.
> 
> Using a Derivative filter from MSL (as in the attached .mo) enables the compilation but the simulation fails : KINSOL fails to solve (low time constant), time step <= 1e-08 s for more than 10 iterations (higher time constant).
> 
> What block have you tried ? Here is mine :
> 
> [IntegratorVariableLimits.txt](https://github.com/dynawo/dynawo/files/8968180/IntegratorVariableLimits.txt)

I just write tD*der(limitMinFiltered) + limitMinFiltered = limitMin;
And then i used der(limitMinFiltered) instead of der(limitMin) (same for max) in the model
