### ISSUE TITLE
CombiTimeTable smoothness not taken into account

### ISSUE THREAD

**Issue by ErwanGuichard49** [dynawo/dynawo#2407]
On the GitHub branch **2363_combitable**, there is a model _CombiTimeTable.mo_ in Dynawo.Electrical.Controls.Basics.

This model includes a parameter Smoothness (an enumeration with five values), which is propagated to the MSL block CombiTimeTable.mo (instanced as combiTimeTable) whose parameter is named smoothness.

On the GitLab branch **502_add_alstom_svarc**, in _dynawo-rte/nrt/data/SVarC/SVarC_Alstom/SVarC.par_, Smoothness can be modified at line 112. The modifications in this file are not propagated in the parameter smoothness, as can be seen in the simulation

Conversely, the parameter Extrapolation is well propagated to extrapolation. Moreover, Smoothness is well propagated under OpenModelica.

**Comment by rosiereflo** [comment]
This is because OpenModelica sees the default value of the Smoothness as a constant and removes the parameter. If we really want to have the Smoothness as a parameter we need to remove the default value given in the .mo.
