### ISSUE TITLE
[Model compilation] some state variables are not properly converted into adept variables

### ISSUE THREAD

**Issue by rosiereflo** [dynawo/dynawo#2428]

**Comment by ErwanGuichard49** [comment]
This issue has to be reopened : the preassembled models using VRAlst and GoverDk6Gt are not compiled, though other preassembled using models with the SecondOrder block are well compiled.

**Comment by ErwanGuichard49** [comment]
Please make sure _GeneratorSynchronousFourWindingsGoverEdfTur2eVRAlst_ and _GeneratorSynchronousFourWindingsGoverDk6GtVRDk6_ are compiled successfully.

**Comment by ErwanGuichard49** [comment]
On branch **515_restore_MSL_SecondOrder**, the compilation of _GeneratorSynchronousFourWindingsGoverEdfTur2eVRAlst_ and _GeneratorSynchronousFourWindingsGoverDk6GtVRDk6_ still fails, although other models with SecondOrder from MSL are compiled successfully.

**Comment by rosiereflo** [comment]
I'll fix this in another issue as it might not be the same one
