### ISSUE TITLE
Print additionnal point in curves output file when there is a change in discrete variables in order to display a step change rather than a  ramp change

### ISSUE THREAD

**Issue by MarianneSaugierRTE** [dynawo/dynawo#243]

**Comment by adriguir** [comment]
As of today, new points (in time) are added to the curves only:

- once the overall time step is done (most of the cases)
- before and after the algebraic equation restoration (twice for the same time step) in case of an algebraic mode detection (corresponding to a brutal event leading to a discontinuity into the J functions).

Indeed, when there is a change into a discrete variable at a time step, we don't see a jump but rather a ramp between the value at the previous time step and the final value at the current time step. To improve the outputs for end-users, it would be better in this case to add a new point corresponding to the past values for the discrete variables before the new point (it ends up with two points for the same time step).
This should be done only in case of a z change and should be done at the simulation level (to avoid duplicating code). It could be done before copying the new z calculated (y should be updated but not z).
