### ISSUE TITLE
Add InjectorIDQ preassembled

### ISSUE THREAD

**Issue by ErwanGuichard49** [dynawo/dynawo#2449]

**Comment by cossartque** [comment]
What is it for ?

**Comment by ErwanGuichard49** [comment]
I have created it in order to include InjectorIDQ in a dyd. This may not be necessary as I will use Modelica as much as possible.

**Comment by cossartque** [comment]
OK, can we close it then ?

**Comment by ErwanGuichard49** [comment]
Yes.
