### ISSUE TITLE
Put PRefPu, QRefPu, URefPu as optional whenever possible and remove setpoints of preassembled models

### ISSUE THREAD

**Issue by cossartque** [dynawo/dynawo#2493]
For all the models with references as continuous extvar, these extvar should be put as optional whenever possible. As a first step, we can look for all the continuous extvar with Ref in the name (except omegaRefPu of course).
Moreover, the setpoints added in the preassembled models should be deleted whenever the extvar is optional.
The same way, the setpoints parameters in the nrt should be removed, as now useless (especially the valueIn).
Finally, the nrt should be checked.

**Comment by ErwanGuichard49** [comment]
Should I replace the discrete reference variables with continuous optional ones in the .extvar ? See HvdcPV for instance.
