### ISSUE TITLE
DynaFlow : Add PRefPu  in generator models

### ISSUE THREAD

**Issue by cossartque** [dynawo/dynawo#2550]
Today, PGenRawPu = - PRef0Pu + Alpha * N; in BaseGeneratorSignalN and BaseGeneratorSignalNSFR.
We should have PGenRawPu = - PRefPu + Alpha * N;
With input Types.ActivePowerPu PRefPu(start = PRef0Pu) "Active power set point in pu (base SnRef) (receptor convention)";

We could do the same for QRefPu

They should be added as continuous optional extvar.

Maybe we should have a look at HVDC and SVarC too.

**Comment by marcochiaramello** [comment]
It is solved in #2221
