### ISSUE TITLE
Nordic test system : filter curves for performance reasons

### ISSUE THREAD

**Issue by cossartque** [dynawo/dynawo#2620]
In OpenModelica, it is possible to filter the curves.
As we don't need all of them in the test case, we could filter them to only have the UPu (U1Pu, U2Pu also),  PGen, QGen.
@adriguir as discussed

**Comment by adriguir** [comment]
I can do it myself if fine for everyone

**Comment by ErwanGuichard49** [comment]
> I can do it myself if fine for everyone

I was ready to do it, but if you know what to do, go ahead.

**Comment by adriguir** [comment]
Unfortunately, as discussed, there seems there is no way to save the variable filter syntax into the annotation for an automatic use.
Therefore I propose to close the issue and stick with the test case as it is.
