### ISSUE TITLE
Fix preassembled model EventSetPointDouble which is actually a single real event

### ISSUE THREAD

**Issue by MarianneSaugierRTE** [dynawo/dynawo#265]

**Comment by MarianneSaugierRTE** [comment]
I find the name EventSetPointDouble misleading.
By the name I thought it was a DoubleRealEvent but it is a SingleRealEvent.
What do you think @adriguir ?

**Comment by adriguir** [comment]
I completely agree, definitely misleading. It could be named EventSetPointReal, even if I don't really like the fact that the variable type appears into the name but I believe we don't have any other option here
