### ISSUE TITLE
xml namespace

### ISSUE THREAD

**Issue by gautierbureau** [dynawo/dynawo#268]
if by mistake in the xml files the namespace is not `xmlns="http://www.rte-france.com/dynawo"` the xml is parsed but the resulting object contains nothing resulting in an error later in Dynawo that could be warned or caught earlier with a clearer message

**Comment by rosiereflo** [comment]
this error is directly sent by xerxes thus I am not sure what could be done here

**Comment by rosiereflo** [comment]
how to reproduce: typo in "http://www.rte-france.com/dynawo" and no xsd validation
