### ISSUE TITLE
Replace French word into Standard Static Var Compensators model

### ISSUE THREAD

**Issue by adriguir** [dynawo/dynawo#2774]
In the Standard SVarC model, a block is called CalculBG, which is French.
It should be translated.

**Comment by cossartque** [comment]
@ErwanGuichard49 we can do something similar to what is done in the specific models

**Comment by ErwanGuichard49** [comment]
> @ErwanGuichard49 we can do something similar to what is done in the specific models

What do you mean ?

I would have translated CalculBG with CalculationBG.
In the specific models, B and G are calculated by Inter models : InterAb2, InterSv2, InterSvc.
