### ISSUE TITLE
Solver prediction and hysteresis

### ISSUE THREAD

**Issue by ErwanGuichard49** [dynawo/dynawo#2817]
On branch master, in the model _dynawo-rte/dynawo/sources/Models/Modelica/DynawoRTE/Electrical/Controls/Machines/VoltageRegulators/Specific/Nuclear/VR4Edf1.mo_, during the simulation of _dynawo-rte/nrt/data/SMIB/SMIB_GoverEdfTur1eVR4Edf1/SMIB.jobs_, the variable hysteresis.u drops suddenly at 1 s.

hysteresis.u exceeded hysteresis.uHigh before the fall, after the fall hysteresis.u is between hysteresis.uLow and hysteresis.uHigh. The output hysteresis.y should theoretically remain true. However, hysteresis.y switches to false when u drops, probably because of a solver prediction of an imminent downward crossing of uLow, which never happens.

Could this solver prediction be ignored ?

**Comment by rosiereflo** [comment]
This is in fact a series of algebraic restorations that are not displayed in the curve files, giving the impression that the boolean shouldn't have switched. However, the input does goes below the low limit in one of those algebraic restoration, this is why the boolean value changes.
