### ISSUE TITLE
Intermediate variables and algebraic/differential variables

### ISSUE THREAD

**Issue by ErwanGuichard49** [dynawo/dynawo#2919]
In the model **DynawoRTE.Electrical.DC.Specific.Inelfe.BaseControls.DcSiem.mo**, two intermediate variables _derIDc1_ and _derIDc2_ are declared and calculated as derivatives of _IDc1_ and _IDc2_ respectively. These intermediate variables are not used.

If I remove these variables and their defining equations (by commenting the lines 50, 51, 64, 65), the compilation of **HvdcInelfe** is successful but the simulation of **nrt/data/HVDC/Inelfe/HVDC.jobs** yields the error

DYN Error: the number of algebraic/differential variables is different from the number of algebraic/differential equations in the simulated problem

**Comment by rosiereflo** [comment]
Hi, those variables are used by OpenModelica to replace differential variables in  equations, thus making the equations algebraic eventually, e.g;
```
myDer = der(a)
b = f(der(a)) // differential
```

becomes
```
myDer = der(a)
b = f(myDer) //algebraic
```

Knowing that we see that initially the model  DcSiem is balanced : 6 algebraics variables/equations and 3 differential variables/equations.
Removing those variables prevents this from happening, and the model is no longer balanced: we have 5 algebraic variables for 2  algebraic equations, which is not supported by Dynawo.
