### ISSUE TITLE
Nrt : verify the compilation of all .tex

### ISSUE THREAD

**Issue by ErwanGuichard49** [dynawo/dynawo#2931]
As part of the non-regression test process, every .tex in the public and RTE libraries should be compiled.

**Comment by rosiereflo** [comment]
This should be part of a nightly and not of nrts

**Comment by ErwanGuichard49** [comment]
By the way, could/should the OpenModelica examples be run as part of a nightly ?

**Comment by rosiereflo** [comment]
> By the way, could/should the OpenModelica examples be run as part of a nightly ?

This is possible, we already tried but it was disabled due to stability issue, we could try again I guess
