### ISSUE TITLE
SMIB examples not directly working in OMEdit

### ISSUE THREAD

**Issue by adriguir** [dynawo/dynawo#2941]
When downloading either the source code or the released version of the Modelica library, the Examples/SMIB/Standard test cases from the Modelica library don't work because the TableFile is not directly found by OMEdit (at least in my case).

With a downloaded version of the code, it is possible to change the path and adapt it. What's not very good is that someone has to retroengineer the info (even if not difficult, could be annoying for a new user).
With the Modelica library from the release, you don't even have access to this file in the download so you are stuck.

I don't really know how this works but would it be possible to have a path that always work (do relative paths work?) or to replace the txt file by a table in the full OM version... 

Not really big deal but a bit annoying.

@cossartque @joyelfeghali FYI

**Comment by cossartque** [comment]
When using a relative path it is from the working directory, which changes from one person to another. What we can do is put a comment/warning in the test case to warn people to change the path accordingly. Also, we will put the txt that are needed in the full OM test cases, directly in the Examples section of the library, just like we did for the recently added DynaFlow illustrative test cases.

@GerardThevenon could you work on this (after a pull on master, new tests have been added) ?
The idea is to:
- First find all the full OM examples that need an external txt file. If it is not directly in the proper folder (we usually refer to a txt in the nrt which is not good), put it there and change the path.
- put a warning in the annotation of the test case to inform the user that the path should be updated according to their working directory.

**Comment by GerardThevenon** [comment]
I believe @ErwanGuichard49 already thought about a solution ?

**Comment by rosiereflo** [comment]
Wouldn't it be cleaner to transpose the file into a Modelica table so that the user can simulte directly?

**Comment by adriguir** [comment]
> Wouldn't it be cleaner to transpose the file into a Modelica table so that the user can simulate directly?

I think so but wouldn't it lead to have two different implementations - one for Dynawo itself, and another for a full Modelica use case?

**Comment by cossartque** [comment]
> > Wouldn't it be cleaner to transpose the file into a Modelica table so that the user can simulate directly?
> 
> I think so but wouldn't it lead to have two different implementations - one for Dynawo itself, and another for a full Modelica use case?

Yes, it will lead to having two models, which is not really what we want

**Comment by ErwanGuichard49** [comment]
There is a Modelica function named Modelica.Utilities.Files.loadResource,  I have tried and failed to use it. As far as I understand, this function is aimed at calling a non-modelica file (.txt) in the Modelica package.

**Comment by adriguir** [comment]
Well done and thank you, that's nice!
