### ISSUE TITLE
SwitchOffSignals/Running Handling - Initially disconnected elements

### ISSUE THREAD

**Issue by adriguir** [dynawo/dynawo#2945]
In the current implementation of the SwitchOff control blocks, an element cannot be disconnected at the beginning of the simulation.
Indeed, running is initialized at true and thus even if someone writes something like:
shuntB.switchOffSignal1.value = false;
the shunt will remain connected all over the simulation.

I have seen some developments on this topic so maybe it no longer applies. Otherwise it would be nice to have running0 as a parameter (State0 doesn't have any impact on the running status...)

@joyelfeghali @cossartque FYI

**Comment by cossartque** [comment]
I'm not sure I understand the question but if you write shuntB.switchOffSignal1.value = true; (and not false), it will be disconnected.

**Comment by adriguir** [comment]
There was a typo indeed: the point is that even if I write this shuntB.switchOffSignal1.value = true;, it remains connected.
For example, if I take the SMIBStepPm example from the Modelica library,  and I modify the switchOffSignal for one transformer in the following manner: 

  transformer.switchOffSignal1.value = true;
  transformer.switchOffSignal2.value = false;

When I look to the plots, I get the following P,Q flows through the transformer (not zero):

![image](https://github.com/dynawo/dynawo/assets/38657764/0d69aa1d-fe1f-473d-86f5-f49c0ced4fb7)

In my understanding, there is no way in the initialization scheme to have running equal to false at the t = 0. And then the when equations driving any update of running are inhibited because switchOffValue1 and switchOffValue2 or 3 are initially true so there is no change during the simulation.

  if (NbSwitchOffSignals >= 3) then
    when switchOffSignal1.value or switchOffSignal2.value or switchOffSignal3.value and pre(running.value) then
      running.value = false;
    elsewhen not switchOffSignal1.value and not switchOffSignal2.value and not switchOffSignal3.value and not pre(running.value) then
      running.value = true;
    end when;
  elseif (NbSwitchOffSignals >= 2) then
    when switchOffSignal1.value or switchOffSignal2.value and pre(running.value) then
      running.value = false;
    elsewhen not switchOffSignal1.value and not switchOffSignal2.value and not pre(running.value) then
      running.value = true;
    end when;
  else
    when switchOffSignal1.value and pre(running.value) then
      running.value = false;
    elsewhen not switchOffSignal1.value and not pre(running.value) then
      running.value = true;
    end when;
  end if;

With Thibault, we had to do something like this to make it work:

when time < 1 then
  transformer.switchOffSignal1.value = false;
else when time >=1 then
   transformer.switchOffSignal1.value = true;
end when;

We haven't found any way to begin with a disconnected component, but maybe there is one!

**Comment by adriguir** [comment]
NB: I can also put the two switchOffSignals equal to true, the transformer is still connected.

**Comment by ErwanGuichard49** [comment]
Please check branch _2945_switchOff_init_. Does it solve this issue ?
