### ISSUE TITLE
[WECC] Incorrect initialization in the Q control mode

### ISSUE THREAD

**Issue by adriguir** [dynawo/dynawo#3018]
In the current implementation, the initialization of the LimPIDFreeze Integrator in the WECC model is not correct.
The correct implementation is available here - https://github.com/bertrtam00/wecc_iec_model_comparison/pulls?q=is%3Apr+is%3Aclosed

**Comment by GerardThevenon** [comment]
@adriguir Do you agree that when #2996 is merged, this issue will be solved?

**Comment by adriguir** [comment]
As we don't have any date for merging of #2996 , I suggest that we go ahead in already fixing this bug.
