### ISSUE TITLE
Add timeline data in SecondaryVoltageControl model

### ISSUE THREAD

**Issue by rosiereflo** [dynawo/dynawo#3042]

**Comment by joyelfeghali** [comment]
@deslooverejul 
1)Add the when loop in the SecondaryVoltageControl to add the Timeline ( like in #2863 )  

2)Build an nrt that tests it (the timeline needs to be asked for in the jobs and added to the references, just like the curves  (like in #2863 )  

3)Add the nrt to the cases.py
