### ISSUE TITLE
[IEC] Add a timeline message when the unit is disconnected by its protections

### ISSUE THREAD

**Issue by louisg-rte** [dynawo/dynawo#3133]
In the current situation, there is no message - neither log nor timeline - when the IEC WPP model is disconnected from the grid by its protections.

We propose to add a timeline message to give the user an indication on what's going on.

@joyelfeghali we can have different levels of implementation, either logging only when the WPP is tripping whatever the reason or trying to have a when condition on each cause of tripping (under/over voltage, under/over frequency). Any preference?

@adriguir FYI

**Comment by joyelfeghali** [comment]
It would be interesting to implement the different conditions for each cause of tripping
