### ISSUE TITLE
better handle complex function

### ISSUE THREAD

**Issue by Philibert92** [dynawo/dynawo#3369]
I tried to build a model with dynawo. This model has several equations in OpenModelica such as the following : 
iqMaxPu = if pqFRTFlag then min(IMaxPu, IQMaxPu) else min(sqrt(max(IMaxPu ^ 2 - ipLVRTPrimPu ^ 2, 0)), IQMaxPu); 

But got the following error:
![image](https://github.com/user-attachments/assets/e9f27428-7c47-4e18-b635-126292bdebcd)

Branch is "3248_IEC63406_model" and the command to obtain this error was "dynawo clean-build-models IEC63406ConverterCurrentSource"

It seems the convolution of min, sqrt and max is not well handled by the script. A related issue seems to have been fixed in issue #3097.

Is it possible to modify the script to handle these kinds of functions ?

**Comment by rosiereflo** [comment]
Could you please provide a branch which triggers this issue? Thanks
