### ISSUE TITLE
Table file in InfiniteBusFromTable model

### ISSUE THREAD

**Issue by marcosmc** [dynawo/dynawo#3403]
In the attached model we have defined a simple case that uses the InfiniteBusFromTable dynamic model, the file with the table for the bus is called TableInfiniteBus.txt, below is the definition in the PAR file of the bus model:
```
<set id="InfiniteBus">
<par type="STRING" name="infiniteBus_UPuTableName" value="TableUPu"/>
<par type="STRING" name="infiniteBus_UPhaseTableName" value="TableUPhase"/>
<par type="STRING" name="infiniteBus_OmegaRefPuTableName" value="TableOmegaRefPu"/>
<par type="STRING" name="infiniteBus_TableFile" value="TableInfiniteBus.txt"/>
</set>

```
If we launch a dynamic simulation from within the case directory (`debian@RMS:~/test$ dynawo.sh jobs TSOModel.jobs`), Dynawo works without problems. 

```
debian@RMS:~/test$ dynawo.sh jobs TSOModel.jobs 
[INFO] xsd validation will not be used
launching job 'Pcs I6  - Synchronous Machine'
job 'Pcs I6  - Synchronous Machine' succeeded
results are available in /home/debian/test/./outputs

```
But if you run it from the parent directory (`debian@RMS:~$ dynawo.sh jobs test/TSOModel.jobs`) it doesn't find the file TableInfiniteBus.txt

```
debian@RMS:~$ dynawo.sh jobs test/TSOModel.jobs 
[INFO] xsd validation will not be used
launching job 'Pcs I6  - Synchronous Machine'
DYN Error: unexpected error while using Modelica library: Not possible to open file "TableInfiniteBus.txt": No such file or directory
 ( DYNModelicaUtilities.cpp:43 )
Dynawo execution failed

```
It seems that the location of the file with the table of values ​​for the bus model depends on the point at which the dynamic simulator is run.

Dynawo version

```
debian@RMS:~/test$ dynawo.sh version
1.7.0 (rev:master-8a23fa6)
```

[test.zip](https://github.com/user-attachments/files/17096750/test.zip)

**Comment by rosiereflo** [comment]
Hi, this is a Modelica limitation, the path of the file is considered to be given relatively to the execution folder. There is nothing we can do to solve this topic on our side.
