### ISSUE TITLE
QGenPu > QGenMaxPu or < QGenMinPu in some configurations for GeneratorPQProp* models

### ISSUE THREAD

**Issue by gaouizer** [dynawo/dynawo#3479]
In GeneratorPQProp* models, in some configurations it might occur that QGenPu > QGenMaxPu or < QGenMinPu because qStatus is not updated with the accurate timing to absorbtionMax or GenerationMax. This might lead to a calculation divergence, especially when the generator is connected to a VRRemote or a Secondary Voltage controller.

**Comment by rosiereflo** [comment]
This is "expected" with the simplified solver case, as we need 1 timestep to take into account the modification of the qstatus

**Comment by gaouizer** [comment]
OK. It seems also that #3483 fixes the issue
