### ISSUE TITLE
TapChangerLock: lockOrder is not used and should be deleted

### ISSUE THREAD

**Issue by MarianneSaugierRTE** [dynawo/dynawo#355]

**Comment by adriguir** [comment]
I think the boolean is there if some other model wants to force the lock order activation in the TapChangerLock.
In particular, this could be the case if an user wants to simulate the effect of the tap changers lock manually in a simulation.

Considering this, I would like to keep the variable and close the issue if it is fine for you, @MarianneSaugierRTE
