### ISSUE TITLE
BlackBox model with no par file

### ISSUE THREAD

**Issue by gautierbureau** [dynawo/dynawo#487]
The test in documentation/resources/exampleExecutables/TestPreassembledNoExternal/SimulationCompiledLib with a simple BlackBox model and no par file (all parameters are defined directly in the Modelica models) should work. DynamicData::getParametersSet should not return a null pointer in the case if (parFile == "" && parId == "")

**Comment by gautierbureau** [comment]
Maybe something like this :
```
shared_ptr<ParametersSet::Impl> params = boost::make_shared<ParametersSet::Impl>("NONE");
return static_pointer_cast<ParametersSet>(params);
```

**Comment by rosiereflo** [comment]
We also need to add those tests into the non-regression testsuite to avoid regressions.
