### ISSUE TITLE
Handle generator initialization with P = Q = 0

### ISSUE THREAD

**Issue by adriguir** [dynawo/dynawo#586]
As of today, the initialization model in synchronous generator fails when both P0 and Q0 are equal to zero.

**Comment by adriguir** [comment]
@MarianneSaugierRTE at first glance, the problem only arises in the Phi0 calculation in the initialization model (BaseClasses_INIT.mo). This variable is never used in any other parts of the model. Would it be ok to delete this phi0?

**Comment by MarianneSaugierRTE** [comment]
yes
