### ISSUE TITLE
Improve logs when the local init fails

### ISSUE THREAD

**Issue by cossartque** [dynawo/dynawo#661]

**Comment by rosiereflo** [comment]
Please be more specific and if possible provide a testcase.

**Comment by cossartque** [comment]
My simulation runs but the init values start at 0 which means that there is an init problem. We checked with Adrien and it seems that it is a local init issue. The message that I can find in the logs is:

2020-02-27 11:18:56 | WARN | the linear solver's setup function failed in an unrecoverable manner
