### ISSUE TITLE
[Modelica Models]: Do not impose the same order in the equations in the different branches of an if 

### ISSUE THREAD

**Issue by rosiereflo** [dynawo/dynawo#739]
Modelica :
 if condition then
    Eq1a  //algebraic
    Eq2a //differential
else
    Eq2b //differential
    Eq1b  //algebraic

results in 2 differential equations in the final model as Eq1a (resp. Eq2a) is grouped with Eq2b (resp Eq1b) and as we consider that if one branch of a if is differential all branches are.

This development has a dependency on Ticket #707.

**Comment by adriguir** [comment]
@rosiereflo I think we can close this one, can't we?

**Comment by rosiereflo** [comment]
The issue is still there and the fix is waiting to be commited (I waited for the release branch to be created as I didn't want this to be in the release), so I propose to not close it. I will probably be able to properly test the dev and merge it this fall.
