### ISSUE TITLE
staticRef and modelica layers

### ISSUE THREAD

**Issue by MarianneSaugierRTE** [dynawo/dynawo#794]
Are modelica layers well handled for staticRefs? @adriguir @rosiereflo 

Example on the staticVarCompensator:
The following doesn't wotk:
`<staticRef` var="SVarC_injector_PInjPu" `staticVar="p"/>`

If we define a variable PPu in SVarC and write PPu = injector.PInjPu in the mo file, the following works:
`<staticRef` var="SVarC_PPu" staticVar="p"/>`

**Comment by adriguir** [comment]
Honestly, I don't know at all and I have never gone into details in this part of the code.
What I can say is that it is the good syntax and it seems to be there in the desc.xml file: SVarC_injector_PInjPu with this wording.

**Comment by rosiereflo** [comment]
Let me take a look

**Comment by rosiereflo** [comment]
Would you have a testcase?

**Comment by MarianneSaugierRTE** [comment]
working on it ;)

**Comment by MarianneSaugierRTE** [comment]
sorry... it seems that my problem was linked to something else: it works fine!
