### ISSUE TITLE
Update README with Python3 compatibility

### ISSUE THREAD

**Issue by gautierbureau** [dynawo/dynawo#804]

**Comment by gautierbureau** [comment]
@rosiereflo can we safely put python3 in requirements ?
Documentation might need update as weel as README

**Comment by rosiereflo** [comment]
Sorry I didn't see that message earlier.
Yes it can be put in the README and doc. However the website promotes the release, so we should wait to update it.
Also, it wasn't tested on windows.

**Comment by gautierbureau** [comment]
I agree for the website. 
I will test it on windows to see if it's ok.
