### ISSUE TITLE
Rewrite not running equation for transformers

### ISSUE THREAD

**Issue by MarianneSaugierRTE** [dynawo/dynawo#827]

**Comment by MarianneSaugierRTE** [comment]
We would like to write
` 
if  running 
...
else
  terminal1.i = Complex(0);
  terminal2.i = Complex(0);
end if
`
But then we got some error in test cases using preassembled models with load + transformer.

**Comment by MarianneSaugierRTE** [comment]
Trying to also change the condition in the load model as follows doesn't work:
`if running ... else PPu=0; QPu=0; end if`

**Comment by MarianneSaugierRTE** [comment]
The error is a fail of solver at initialization stage

**Comment by rosiereflo** [comment]
Is there a branch I could use to make sure this is not caused by the model compilation?

**Comment by MarianneSaugierRTE** [comment]
Yes, I just pushed it: 827_running_tfo_load. Thanks for having a look!

**Comment by rosiereflo** [comment]
I don't see anything weird in the generated files. For some reason kinsol is not able to solve the system with this form (I didn't have a deep look at what happens in the solver yet). @adriguir any hint?

**Comment by adriguir** [comment]
I put all my hopes and expectations onto the #739 ;(
I haven't yet had a look to it, will let you know once done

**Comment by rosiereflo** [comment]
Yes I had the same idea, but in this case all equations are ALGEBRAIC :'(

**Comment by adriguir** [comment]
What is strange is that anyway, this branch of the if shouldn't be evaluated. Or do we have an event disconnecting the transformer/load?

**Comment by MarianneSaugierRTE** [comment]
Exactly!!! The failure occurs at init... and normally all running=true....

**Comment by MarianneSaugierRTE** [comment]
Eventually it is the expected behavior to explicitly set the voltage to zero for any network injection
