### ISSUE TITLE
Complex parameters not appearing as readOnly

### ISSUE THREAD

**Issue by adriguir** [dynawo/dynawo#842]
When you have a complex attribute that is a final parameter, it seems we are still obliged to fill it in the .par file, which doesn't seem to be a correct behavior.

For example, if we modify the BaseGeneratorSimplified_INIT in the following way:

  public
    parameter Types.ActivePowerPu P0Pu  "Start value of active power at terminal in p.u (base SnRef) (receptor convention)";
    parameter Types.ReactivePowerPu Q0Pu  "Start value of reactive power at terminal in p.u (base SnRef) (receptor convention)";
    parameter Types.VoltageModulePu U0Pu "Start value of voltage amplitude at terminal in p.u (base UNom)";
    parameter Types.Angle UPhase0  "Start value of voltage angle at terminal in rad";

  protected
    final parameter Types.ActivePowerPu PGen0Pu = -P0Pu "Start value of active power at terminal in p.u (base SnRef) (generator convention)";
    final parameter Types.ReactivePowerPu QGen0Pu = -Q0Pu "Start value of reactive power at terminal in p.u (base SnRef) (generator convention)";

    final parameter Types.ComplexVoltagePu u0Pu = ComplexMath.fromPolar(U0Pu, UPhase0) "Start value of complex voltage at terminal in p.u (base UNom)";
    final parameter Types.ComplexApparentPowerPu s0Pu = Complex(P0Pu, Q0Pu) "Start value of complex apparent power at terminal in p.u (base SnRef) (receptor convention)";
    final parameter Types.ComplexCurrentPu i0Pu = ComplexMath.conj(s0Pu / u0Pu)  "Start value of complex current at terminal in p.u (base UNom, SnRef) (receptor convention)";

I would have expected that the s0Pu, u0Pu and i0Pu parameters are read-only (as PGen0Pu and QGen0Pu). It works fine for the last two but not for the complex ones.

**Comment by adriguir** [comment]
@MarianneSaugierRTE @rosiereflo what is your opinion? Shouldn't they be internal parameters?

**Comment by MarianneSaugierRTE** [comment]
I don't know what it means in terms of implementation but yes it should work for s0Pu same as PGen0Pu

**Comment by rosiereflo** [comment]
You are both right, they should be internal and not needed in the par file. Any branch that I can use to investigate?

**Comment by adriguir** [comment]
I pushed the branch 842_TestFinalParameters to provide a test case.
