### ISSUE TITLE
Detect z modifications implementation

### ISSUE THREAD

**Issue by adriguir** [dynawo/dynawo#875]
In the current implementation, in the ModelMulti evalZ method, we first evaluate z into the different sub models and then detect if there has been a z change by comparing one by one the new z with the saved ones. After this, the z are potentially propagated and we copy the new z to save them for the next evaluation.

One other possible implementation would be to make the evalZ method returning the z differences positions into the vector and let them handle locally the differences analysis.

**Comment by rosiereflo** [comment]
Following issue #894 the expected improvement associated to this ticket is low, thus we can skip it for now.
