### ISSUE TITLE
Avoid the copy done in the algebraic restoration in evalF

### ISSUE THREAD

**Issue by adriguir** [dynawo/dynawo#891]
When doing an algebraic restoration or problem reinitialization, only a part of the system is calculated (either the algebraic one or the differential one).
Nevertheless, as there is no way to only call evalF on the algebraic part or the differential part and that we use direct memory access, we call a complete evalF evaluation and then we copy the necessary f into the Kinsol structure (only a subpart of the global F).

The objective would be to avoid the copy and to be able to directly modify the Kinsol structure.

**Comment by rosiereflo** [comment]
After analysis there is no easy way to improve further this as the solver is working on a subset of variables that might change over time.
When cpp98 will be dropped we could take a look if std in cpp11 is offering partial table copy methods to go faster.
