### ISSUE TITLE
Simplify Voltage regulators initialization

### ISSUE THREAD

**Issue by RomainLosseauRTE** [dynawo/dynawo#92]
- initialize directly from machine's UStatorPu, not from machine complex voltage u0

**Comment by adriguir** [comment]
@RomainLosseauRTE do you remember what was the possible simplifications or the open questions?

**Comment by RomainLosseauRTE** [comment]
> @RomainLosseauRTE do you remember what were the possible simplifications or the open questions?

It is just that we initialize starting from u0Pu and then compute UstatorPu0, we could spare one equation if we connect directly to the UstatorPu0 computed in the machine init model ?
