### ISSUE TITLE
Update curves enhancement

### ISSUE THREAD

**Issue by adriguir** [dynawo/dynawo#922]
In the current implementation, the update curves does more or less the same treatment whatever is the way and in which part of the process it is called. 

However, when the update is done after a z change, only z variables have changed values and then some optimization is possible. 

It has to be checked but I think that calculated variables could be skipped.

**Comment by rosiereflo** [comment]
The first call to update curve needs it as we need to update all the curves. However, you are right: the second one does not need the calc var update (it would look like this : updateCurves(!isCheckCriteriaIter && !solverState.getFlags(ZChange)))
