### ISSUE TITLE
Enable to apply xsl script in another folder than nrt

### ISSUE THREAD

**Issue by MarianneSaugierRTE** [dynawo/dynawo#945]

**Comment by rosiereflo** [comment]
Hi, this is possible with the option --jobs=<job_file>

**Comment by MarianneSaugierRTE** [comment]
can it run on all the test cases of a directory? I would like to give a folder in argument...

**Comment by rosiereflo** [comment]
Not today, mainly due to the fact that we cannot guess how the jobs file will be named. I could add a lookup for .jobs and fic_JOB.xml files if you want.

**Comment by gautierbureau** [comment]
Another useful case would be to update par without a jobs (for powsybl-dynawo)
