### ISSUE TITLE
Study the possibility to handle connections by propagating a unique value instead of  adding a a=b equation

### ISSUE THREAD

**Issue by rosiereflo** [dynawo/dynawo#964]

**Comment by adriguir** [comment]
@rosiereflo should we close it or let it as on-hold?
I understood from past discussions that the implementation would be very tricky for a gain that you judge limited.

**Comment by rosiereflo** [comment]
this one is very tricky and would probably need us to re-question the modes organization. However the gain would be significant.
To be honest I don't even know if that's feasible.

**Comment by rosiereflo** [comment]
Performance gains are low for a lot of modified code so I close this ticket
