### ISSUE TITLE
Create a specific visual image for HVDC line

### ISSUE THREAD

**Issue by adriguir** [dynawo/dynawo#969]
I think it would be nice to have a specific icon for HVDC lines different from AC lines.
Any suggestion @MarianneSaugierRTE @cossartque @RomainLosseauRTE @marcochiaramello ?

**Comment by MarianneSaugierRTE** [comment]
Two squares linked by two lines, and if we have room in the squares we can write AC/DC or draw a wave and a steady line (for the converter) ?

**Comment by adriguir** [comment]
I will try and let you know.

**Comment by MarianneSaugierRTE** [comment]
Or just a reactangle with two pins and written HVDC inside, more and enough for know I think! (and what we have for the HVDC VSC, it took me a while to remember)
