### ISSUE TITLE
Add a dynamic to GeneratorPV

### ISSUE THREAD

**Issue by MarianneSaugierRTE** [dynawo/dynawo#992]
in order to decouple discrete events with generator behavior

**Comment by MarianneSaugierRTE** [comment]
Some tests show that adding a deadband is not enough, we need to add a dynamic with a time constant T. The value of T is set inside the Modelica model and is set experimentally to 1s.

**Comment by rosiereflo** [comment]
If this is supposed to go into the v1.2.0 release, please add v1.2.0 into the Milestone

**Comment by MarianneSaugierRTE** [comment]
ok, thanks I didn't know there was a milestone ;)

**Comment by rosiereflo** [comment]
brand new!
