### ISSUE TITLE
Add a specific compilation variable for performance measurement

### ISSUE THREAD

**Issue by adriguir** [dynawo/dynawo#999]
In the current implementation, the structure and use of the timers is compiled only if in debug mode, which is not compatible with performance measurements.
In addition, each timer construction is also protected by a ifdef DEBUG instruction (or will be in the future).

As a result, doing performances measurements is quite painful and always required to modify the files. 

I would suggest having a specific compilation variable for performance measurements. @gautierbureau @rosiereflo what do you think?

**Comment by rosiereflo** [comment]
Sound good
